import { render,screen,fireEvent,cleanup } from '@testing-library/react';
import { afterEach,it,expect,vi } from 'vitest';
import DailyUsage from './DailyUsage';
import { MemoryRouter } from 'react-router-dom';
vi.mock('@/components/AppNavigation',()=>({AppNavigation:()=>null}));
vi.mock('@/components/StockSummary',()=>({StockSummary:()=>null}));
vi.mock('@/components/UnifiedShift',()=>({UnifiedShift:({date,onDirtyChange}:{date:string;onDirtyChange:(dirty:boolean)=>void})=><button onClick={()=>onDirtyChange(true)}>Draft for {date}</button>}));
afterEach(()=>{cleanup();vi.restoreAllMocks();});
it('keeps the selected day when a draft navigation is cancelled, then permits previous day after confirmation',()=>{
 const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);
 render(<MemoryRouter><DailyUsage/></MemoryRouter>);
 const date=screen.getByLabelText('Date') as HTMLInputElement;const initial=date.value;
 fireEvent.click(screen.getByText(`Draft for ${initial}`));
 expect(date).not.toBeDisabled();
 fireEvent.click(screen.getByRole('button',{name:'Previous day'}));
 expect(confirm).toHaveBeenCalledWith(expect.stringContaining('stay saved as a draft'));
 expect(date.value).toBe(initial);
 confirm.mockReturnValue(true);
 fireEvent.click(screen.getByRole('button',{name:'Previous day'}));
 expect(date.value).not.toBe(initial);
});
